version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: guarabrecho_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: guarabrecho
      POSTGRES_USER: guarabrecho_user
      POSTGRES_PASSWORD: guarabrecho_pass
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - guarabrecho_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: guarabrecho_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@guarabrecho.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - guarabrecho_network

volumes:
  postgres_data:

networks:
  guarabrecho_network:
    driver: bridge
